FROM microsoft/windowsservercore

# Windows instructions are here
# https://github.com/symless/synergy-core/wiki/Compiling
# But it's quite involved, and not easily scriptable. :(

# RUN apt-get update && \
#     apt-get install -y \
#         qtcreator qtbase5-dev \
#         cmake make g++ \
#         xorg-dev libssl-dev \
#         libx11-dev libsodium-dev \
#         libgl1-mesa-glx libegl1-mesa \
#         libcurl4-openssl-dev \
#         libavahi-compat-libdnssd-dev \
#         qtdeclarative5-dev \
#         libqt5svg5-dev \
#         libsystemd-dev \
#         git bash
# ENV BOOST_ROOT /root/boost

# Mount source code
# Use the -v flag to mount volume correctly

# Build it!
# RUN mkdir /root/synergy-core && chmod +x /root && chmod +x /root/synergy-core
#ENTRYPOINT [ "/root" ]
